#include "firmware/mini_board.h"

#include "ARMCM0.h"
#include "bsp/dp32g030/gpio.h"
#include "bsp/dp32g030/portcon.h"
#include "bsp/dp32g030/syscon.h"
#include "driver/bk4819.h"
#include "driver/gpio.h"
#include "driver/st7565.h"
#include "driver/system.h"
#include "driver/systick.h"

#define IDE_PIN_ENCODE(port, number)  ((((uint8_t)(port)) << 5) | ((number) & 0x1FU))

enum {
	// GPIOA free pins
	IDE_PIN_PA0  = IDE_PIN_ENCODE(0U, 0U),
	IDE_PIN_PA1  = IDE_PIN_ENCODE(0U, 1U),
	IDE_PIN_PA2  = IDE_PIN_ENCODE(0U, 2U),
	IDE_PIN_PA15 = IDE_PIN_ENCODE(0U, 15U),
	
	// GPIOB pins (original 2 + new free pins)
	IDE_PIN_PB0  = IDE_PIN_ENCODE(1U, 0U),
	IDE_PIN_PB1  = IDE_PIN_ENCODE(1U, 1U),
	IDE_PIN_PB2  = IDE_PIN_ENCODE(1U, 2U),
	IDE_PIN_PB3  = IDE_PIN_ENCODE(1U, 3U),
	IDE_PIN_PB4  = IDE_PIN_ENCODE(1U, 4U),
	IDE_PIN_PB5  = IDE_PIN_ENCODE(1U, 5U),
	IDE_PIN_PB6  = IDE_PIN_ENCODE(1U, 6U),
	IDE_PIN_PB12 = IDE_PIN_ENCODE(1U, 12U),
	IDE_PIN_PB13 = IDE_PIN_ENCODE(1U, 13U),
	IDE_PIN_PB14 = IDE_PIN_ENCODE(1U, 14U),
	
	// GPIOC pins (original + new free pins)
	IDE_PIN_PC3  = IDE_PIN_ENCODE(2U, 3U),
	IDE_PIN_PC5  = IDE_PIN_ENCODE(2U, 5U),
	IDE_PIN_PC6  = IDE_PIN_ENCODE(2U, 6U),
	IDE_PIN_PC7  = IDE_PIN_ENCODE(2U, 7U),
	IDE_PIN_PC8  = IDE_PIN_ENCODE(2U, 8U),
	IDE_PIN_PC9  = IDE_PIN_ENCODE(2U, 9U),
	IDE_PIN_PC10 = IDE_PIN_ENCODE(2U, 10U),
	IDE_PIN_PC11 = IDE_PIN_ENCODE(2U, 11U),
	IDE_PIN_PC12 = IDE_PIN_ENCODE(2U, 12U),
	IDE_PIN_PC13 = IDE_PIN_ENCODE(2U, 13U),
	IDE_PIN_PC14 = IDE_PIN_ENCODE(2U, 14U),
	IDE_PIN_PC15 = IDE_PIN_ENCODE(2U, 15U),
};

static volatile GPIO_Bank_t *IDE_BOARD_GetBank(mini_pin_t pin)
{
	switch (pin >> 5) {
	case 0:
		return GPIOA;
	case 1:
		return GPIOB;
	case 2:
		return GPIOC;
	default:
		return GPIOA;
	}
}

static void IDE_BOARD_EnableClocks(void)
{
	SYSCON_DEV_CLK_GATE = 0
		| SYSCON_DEV_CLK_GATE_GPIOA_BITS_ENABLE
		| SYSCON_DEV_CLK_GATE_GPIOB_BITS_ENABLE
		| SYSCON_DEV_CLK_GATE_GPIOC_BITS_ENABLE
		| SYSCON_DEV_CLK_GATE_SPI0_BITS_ENABLE
		;
}

static void IDE_BOARD_InitGpio(void)
{
	GPIOA->DIR |= GPIO_DIR_10_BITS_OUTPUT | GPIO_DIR_11_BITS_OUTPUT | GPIO_DIR_12_BITS_OUTPUT | GPIO_DIR_13_BITS_OUTPUT;
	GPIOA->DIR &= ~(GPIO_DIR_3_MASK | GPIO_DIR_4_MASK | GPIO_DIR_5_MASK | GPIO_DIR_6_MASK);

	GPIOB->DIR |= GPIO_DIR_6_BITS_OUTPUT | GPIO_DIR_9_BITS_OUTPUT | GPIO_DIR_11_BITS_OUTPUT | GPIO_DIR_14_BITS_OUTPUT;
	GPIOB->DIR &= ~(GPIO_DIR_7_MASK | GPIO_DIR_8_MASK | GPIO_DIR_10_MASK);

	GPIOC->DIR |= GPIO_DIR_0_BITS_OUTPUT | GPIO_DIR_1_BITS_OUTPUT | GPIO_DIR_2_BITS_OUTPUT | GPIO_DIR_3_BITS_OUTPUT | GPIO_DIR_4_BITS_OUTPUT;
	GPIOC->DIR &= ~(GPIO_DIR_5_MASK);

	GPIO_SetBit(&GPIOA->DATA, 10);
	GPIO_SetBit(&GPIOA->DATA, 11);
	GPIO_ClearBit(&GPIOA->DATA, 12);
	GPIO_SetBit(&GPIOA->DATA, 13);

	GPIO_SetBit(&GPIOB->DATA, 6);
	GPIO_ClearBit(&GPIOB->DATA, 14);
	GPIO_SetBit(&GPIOC->DATA, 0);
	GPIO_SetBit(&GPIOC->DATA, 1);
	GPIO_SetBit(&GPIOC->DATA, 2);
	GPIO_ClearBit(&GPIOC->DATA, 3);
	GPIO_ClearBit(&GPIOC->DATA, 4);
}

static void IDE_BOARD_InitPortcon(void)
{
	PORTCON_PORTA_SEL0 &= ~(PORTCON_PORTA_SEL0_A3_MASK | PORTCON_PORTA_SEL0_A4_MASK | PORTCON_PORTA_SEL0_A5_MASK | PORTCON_PORTA_SEL0_A6_MASK);
	PORTCON_PORTA_SEL0 |= PORTCON_PORTA_SEL0_A3_BITS_GPIOA3 | PORTCON_PORTA_SEL0_A4_BITS_GPIOA4 | PORTCON_PORTA_SEL0_A5_BITS_GPIOA5 | PORTCON_PORTA_SEL0_A6_BITS_GPIOA6;

	PORTCON_PORTA_SEL1 &= ~(PORTCON_PORTA_SEL1_A10_MASK | PORTCON_PORTA_SEL1_A11_MASK | PORTCON_PORTA_SEL1_A12_MASK | PORTCON_PORTA_SEL1_A13_MASK);
	PORTCON_PORTA_SEL1 |= PORTCON_PORTA_SEL1_A10_BITS_GPIOA10 | PORTCON_PORTA_SEL1_A11_BITS_GPIOA11 | PORTCON_PORTA_SEL1_A12_BITS_GPIOA12 | PORTCON_PORTA_SEL1_A13_BITS_GPIOA13;

	PORTCON_PORTB_SEL0 &= ~(PORTCON_PORTB_SEL0_B6_MASK | PORTCON_PORTB_SEL0_B7_MASK);
	PORTCON_PORTB_SEL0 |= PORTCON_PORTB_SEL0_B6_BITS_GPIOB6 | PORTCON_PORTB_SEL0_B7_BITS_SPI0_SSN;

	PORTCON_PORTB_SEL1 &= ~(PORTCON_PORTB_SEL1_B8_MASK | PORTCON_PORTB_SEL1_B9_MASK | PORTCON_PORTB_SEL1_B10_MASK | PORTCON_PORTB_SEL1_B11_MASK | PORTCON_PORTB_SEL1_B14_MASK);
	PORTCON_PORTB_SEL1 |= PORTCON_PORTB_SEL1_B8_BITS_SPI0_CLK | PORTCON_PORTB_SEL1_B9_BITS_GPIOB9 | PORTCON_PORTB_SEL1_B10_BITS_SPI0_MOSI | PORTCON_PORTB_SEL1_B11_BITS_GPIOB11 | PORTCON_PORTB_SEL1_B14_BITS_GPIOB14;

	PORTCON_PORTC_SEL0 &= ~(PORTCON_PORTC_SEL0_C0_MASK | PORTCON_PORTC_SEL0_C1_MASK | PORTCON_PORTC_SEL0_C2_MASK | PORTCON_PORTC_SEL0_C3_MASK | PORTCON_PORTC_SEL0_C4_MASK | PORTCON_PORTC_SEL0_C5_MASK);

	PORTCON_PORTA_IE |= PORTCON_PORTA_IE_A3_BITS_ENABLE | PORTCON_PORTA_IE_A4_BITS_ENABLE | PORTCON_PORTA_IE_A5_BITS_ENABLE | PORTCON_PORTA_IE_A6_BITS_ENABLE;
	PORTCON_PORTA_IE &= ~(PORTCON_PORTA_IE_A10_MASK | PORTCON_PORTA_IE_A11_MASK | PORTCON_PORTA_IE_A12_MASK | PORTCON_PORTA_IE_A13_MASK);

	PORTCON_PORTA_PU |= PORTCON_PORTA_PU_A3_BITS_ENABLE | PORTCON_PORTA_PU_A4_BITS_ENABLE | PORTCON_PORTA_PU_A5_BITS_ENABLE | PORTCON_PORTA_PU_A6_BITS_ENABLE;
	PORTCON_PORTA_PU &= ~(PORTCON_PORTA_PU_A10_MASK | PORTCON_PORTA_PU_A11_MASK | PORTCON_PORTA_PU_A12_MASK | PORTCON_PORTA_PU_A13_MASK);
	PORTCON_PORTA_PD &= ~(PORTCON_PORTA_PD_A3_MASK | PORTCON_PORTA_PD_A4_MASK | PORTCON_PORTA_PD_A5_MASK | PORTCON_PORTA_PD_A6_MASK | PORTCON_PORTA_PD_A10_MASK | PORTCON_PORTA_PD_A11_MASK | PORTCON_PORTA_PD_A12_MASK | PORTCON_PORTA_PD_A13_MASK);
	PORTCON_PORTA_OD |= PORTCON_PORTA_OD_A3_BITS_ENABLE | PORTCON_PORTA_OD_A4_BITS_ENABLE | PORTCON_PORTA_OD_A5_BITS_ENABLE | PORTCON_PORTA_OD_A6_BITS_ENABLE;
	PORTCON_PORTA_OD &= ~(PORTCON_PORTA_OD_A10_MASK | PORTCON_PORTA_OD_A11_MASK | PORTCON_PORTA_OD_A12_MASK | PORTCON_PORTA_OD_A13_MASK);

	PORTCON_PORTB_IE &= ~(PORTCON_PORTB_IE_B6_MASK | PORTCON_PORTB_IE_B7_MASK | PORTCON_PORTB_IE_B8_MASK | PORTCON_PORTB_IE_B9_MASK | PORTCON_PORTB_IE_B10_MASK | PORTCON_PORTB_IE_B11_MASK | PORTCON_PORTB_IE_B14_MASK);
	PORTCON_PORTB_PU &= ~(PORTCON_PORTB_PU_B6_MASK | PORTCON_PORTB_PU_B7_MASK | PORTCON_PORTB_PU_B8_MASK | PORTCON_PORTB_PU_B9_MASK | PORTCON_PORTB_PU_B10_MASK | PORTCON_PORTB_PU_B11_MASK | PORTCON_PORTB_PU_B14_MASK);
	PORTCON_PORTB_PD &= ~(PORTCON_PORTB_PD_B6_MASK | PORTCON_PORTB_PD_B7_MASK | PORTCON_PORTB_PD_B8_MASK | PORTCON_PORTB_PD_B9_MASK | PORTCON_PORTB_PD_B10_MASK | PORTCON_PORTB_PD_B11_MASK | PORTCON_PORTB_PD_B14_MASK);
	PORTCON_PORTB_OD &= ~(PORTCON_PORTB_OD_B6_MASK | PORTCON_PORTB_OD_B9_MASK | PORTCON_PORTB_OD_B11_MASK | PORTCON_PORTB_OD_B14_MASK);

	PORTCON_PORTC_IE |= PORTCON_PORTC_IE_C5_BITS_ENABLE;
	PORTCON_PORTC_IE &= ~(PORTCON_PORTC_IE_C0_MASK | PORTCON_PORTC_IE_C1_MASK | PORTCON_PORTC_IE_C2_MASK | PORTCON_PORTC_IE_C3_MASK | PORTCON_PORTC_IE_C4_MASK);
	PORTCON_PORTC_PU |= PORTCON_PORTC_PU_C5_BITS_ENABLE;
	PORTCON_PORTC_PU &= ~(PORTCON_PORTC_PU_C0_MASK | PORTCON_PORTC_PU_C1_MASK | PORTCON_PORTC_PU_C2_MASK | PORTCON_PORTC_PU_C3_MASK | PORTCON_PORTC_PU_C4_MASK);
	PORTCON_PORTC_PD &= ~(PORTCON_PORTC_PD_C0_MASK | PORTCON_PORTC_PD_C1_MASK | PORTCON_PORTC_PD_C2_MASK | PORTCON_PORTC_PD_C3_MASK | PORTCON_PORTC_PD_C4_MASK | PORTCON_PORTC_PD_C5_MASK);
	PORTCON_PORTC_OD &= ~(PORTCON_PORTC_OD_C0_MASK | PORTCON_PORTC_OD_C1_MASK | PORTCON_PORTC_OD_C2_MASK | PORTCON_PORTC_OD_C3_MASK | PORTCON_PORTC_OD_C4_MASK);
	PORTCON_PORTC_OD |= PORTCON_PORTC_OD_C0_BITS_DISABLE | PORTCON_PORTC_OD_C1_BITS_DISABLE | PORTCON_PORTC_OD_C2_BITS_DISABLE | PORTCON_PORTC_OD_C3_BITS_DISABLE | PORTCON_PORTC_OD_C4_BITS_DISABLE | PORTCON_PORTC_OD_C5_BITS_ENABLE;
}

void IDE_BOARD_Init(void)
{
	SYSTEM_ConfigureClocks();
	IDE_BOARD_EnableClocks();
	SYSTICK_Init();
	IDE_BOARD_InitPortcon();
	IDE_BOARD_InitGpio();
	BK4819_Init();
	ST7565_Init();
	__enable_irq();
}

void IDE_BOARD_ResetScriptPins(void)
{
	IDE_BOARD_BeepStop();

	// Reset all GPIOA free pins to safe state
	IDE_BOARD_PinMode(IDE_PIN_PA0, MINI_PIN_MODE_OUT);
	IDE_BOARD_DigitalWrite(IDE_PIN_PA0, false);
	IDE_BOARD_PinMode(IDE_PIN_PA1, MINI_PIN_MODE_OUT);
	IDE_BOARD_DigitalWrite(IDE_PIN_PA1, false);
	IDE_BOARD_PinMode(IDE_PIN_PA2, MINI_PIN_MODE_OUT);
	IDE_BOARD_DigitalWrite(IDE_PIN_PA2, false);
	IDE_BOARD_PinMode(IDE_PIN_PA15, MINI_PIN_MODE_OUT);
	IDE_BOARD_DigitalWrite(IDE_PIN_PA15, false);

	// Reset all GPIOB free pins to safe state
	IDE_BOARD_PinMode(IDE_PIN_PB0, MINI_PIN_MODE_OUT);
	IDE_BOARD_DigitalWrite(IDE_PIN_PB0, false);
	IDE_BOARD_PinMode(IDE_PIN_PB1, MINI_PIN_MODE_OUT);
	IDE_BOARD_DigitalWrite(IDE_PIN_PB1, false);
	IDE_BOARD_PinMode(IDE_PIN_PB2, MINI_PIN_MODE_OUT);
	IDE_BOARD_DigitalWrite(IDE_PIN_PB2, false);
	IDE_BOARD_PinMode(IDE_PIN_PB3, MINI_PIN_MODE_OUT);
	IDE_BOARD_DigitalWrite(IDE_PIN_PB3, false);
	IDE_BOARD_PinMode(IDE_PIN_PB4, MINI_PIN_MODE_OUT);
	IDE_BOARD_DigitalWrite(IDE_PIN_PB4, false);
	IDE_BOARD_PinMode(IDE_PIN_PB5, MINI_PIN_MODE_OUT);
	IDE_BOARD_DigitalWrite(IDE_PIN_PB5, false);
	IDE_BOARD_PinMode(IDE_PIN_PB12, MINI_PIN_MODE_OUT);
	IDE_BOARD_DigitalWrite(IDE_PIN_PB12, false);
	IDE_BOARD_PinMode(IDE_PIN_PB13, MINI_PIN_MODE_OUT);
	IDE_BOARD_DigitalWrite(IDE_PIN_PB13, false);

	// Reset original pins plus new PC free pins
	IDE_BOARD_PinMode(IDE_PIN_PB14, MINI_PIN_MODE_OUT);
	IDE_BOARD_DigitalWrite(IDE_PIN_PB14, false);

	IDE_BOARD_PinMode(IDE_PIN_PC3, MINI_PIN_MODE_OUT);
	IDE_BOARD_DigitalWrite(IDE_PIN_PC3, false);

	// Reset all GPIOC free pins to safe state
	IDE_BOARD_PinMode(IDE_PIN_PC6, MINI_PIN_MODE_OUT);
	IDE_BOARD_DigitalWrite(IDE_PIN_PC6, false);
	IDE_BOARD_PinMode(IDE_PIN_PC7, MINI_PIN_MODE_OUT);
	IDE_BOARD_DigitalWrite(IDE_PIN_PC7, false);
	IDE_BOARD_PinMode(IDE_PIN_PC8, MINI_PIN_MODE_OUT);
	IDE_BOARD_DigitalWrite(IDE_PIN_PC8, false);
	IDE_BOARD_PinMode(IDE_PIN_PC9, MINI_PIN_MODE_OUT);
	IDE_BOARD_DigitalWrite(IDE_PIN_PC9, false);
	IDE_BOARD_PinMode(IDE_PIN_PC10, MINI_PIN_MODE_OUT);
	IDE_BOARD_DigitalWrite(IDE_PIN_PC10, false);
	IDE_BOARD_PinMode(IDE_PIN_PC11, MINI_PIN_MODE_OUT);
	IDE_BOARD_DigitalWrite(IDE_PIN_PC11, false);
	IDE_BOARD_PinMode(IDE_PIN_PC12, MINI_PIN_MODE_OUT);
	IDE_BOARD_DigitalWrite(IDE_PIN_PC12, false);
	IDE_BOARD_PinMode(IDE_PIN_PC13, MINI_PIN_MODE_OUT);
	IDE_BOARD_DigitalWrite(IDE_PIN_PC13, false);
	IDE_BOARD_PinMode(IDE_PIN_PC14, MINI_PIN_MODE_OUT);
	IDE_BOARD_DigitalWrite(IDE_PIN_PC14, false);
	IDE_BOARD_PinMode(IDE_PIN_PC15, MINI_PIN_MODE_OUT);
	IDE_BOARD_DigitalWrite(IDE_PIN_PC15, false);

	IDE_BOARD_PinMode(IDE_PIN_PC5, MINI_PIN_MODE_IN);
}

bool IDE_BOARD_IsSupportedPin(mini_pin_t pin)
{
	// GPIOA free pins
	if (pin == IDE_PIN_PA0 || pin == IDE_PIN_PA1 || pin == IDE_PIN_PA2 || pin == IDE_PIN_PA15) {
		return true;
	}
	// GPIOB free and safe pins
	if (pin == IDE_PIN_PB0 || pin == IDE_PIN_PB1 || pin == IDE_PIN_PB2 || pin == IDE_PIN_PB3 ||
	    pin == IDE_PIN_PB4 || pin == IDE_PIN_PB5 || pin == IDE_PIN_PB6 || pin == IDE_PIN_PB12 ||
	    pin == IDE_PIN_PB13 || pin == IDE_PIN_PB14) {
		return true;
	}
	// GPIOC free and safe pins
	if (pin == IDE_PIN_PC3 || pin == IDE_PIN_PC5 || pin == IDE_PIN_PC6 || pin == IDE_PIN_PC7 ||
	    pin == IDE_PIN_PC8 || pin == IDE_PIN_PC9 || pin == IDE_PIN_PC10 || pin == IDE_PIN_PC11 ||
	    pin == IDE_PIN_PC12 || pin == IDE_PIN_PC13 || pin == IDE_PIN_PC14 || pin == IDE_PIN_PC15) {
		return true;
	}
	return false;
}

void IDE_BOARD_PinMode(mini_pin_t pin, mini_pin_mode_t mode)
{
	volatile GPIO_Bank_t *bank;
	const uint32_t mask = 1U << MINI_PinNumber(pin);

	if (!IDE_BOARD_IsSupportedPin(pin)) {
		return;
	}

	switch (pin) {
	// GPIOA free pins - basic GPIO setup
	case IDE_PIN_PA0:
	case IDE_PIN_PA1:
	case IDE_PIN_PA2:
	case IDE_PIN_PA15:
		// These are free pins, configure as GPIO
		PORTCON_PORTA_IE &= ~(1U << MINI_PinNumber(pin));
		PORTCON_PORTA_PU &= ~(1U << MINI_PinNumber(pin));
		PORTCON_PORTA_PD &= ~(1U << MINI_PinNumber(pin));
		PORTCON_PORTA_OD &= ~(1U << MINI_PinNumber(pin));
		break;

	// GPIOB pins
	case IDE_PIN_PB0:
	case IDE_PIN_PB1:
	case IDE_PIN_PB2:
	case IDE_PIN_PB3:
	case IDE_PIN_PB4:
	case IDE_PIN_PB5:
		// Free pins in lower range
		PORTCON_PORTB_IE &= ~(1U << MINI_PinNumber(pin));
		PORTCON_PORTB_PU &= ~(1U << MINI_PinNumber(pin));
		PORTCON_PORTB_PD &= ~(1U << MINI_PinNumber(pin));
		PORTCON_PORTB_OD &= ~(1U << MINI_PinNumber(pin));
		break;

	case IDE_PIN_PB6:
		PORTCON_PORTB_SEL0 = (PORTCON_PORTB_SEL0 & ~PORTCON_PORTB_SEL0_B6_MASK) | PORTCON_PORTB_SEL0_B6_BITS_GPIOB6;
		PORTCON_PORTB_IE &= ~PORTCON_PORTB_IE_B6_MASK;
		PORTCON_PORTB_PU &= ~PORTCON_PORTB_PU_B6_MASK;
		PORTCON_PORTB_PD &= ~PORTCON_PORTB_PD_B6_MASK;
		PORTCON_PORTB_OD &= ~PORTCON_PORTB_OD_B6_MASK;
		break;

	case IDE_PIN_PB12:
	case IDE_PIN_PB13:
		// Free pins in middle range
		PORTCON_PORTB_IE &= ~(1U << MINI_PinNumber(pin));
		PORTCON_PORTB_PU &= ~(1U << MINI_PinNumber(pin));
		PORTCON_PORTB_PD &= ~(1U << MINI_PinNumber(pin));
		PORTCON_PORTB_OD &= ~(1U << MINI_PinNumber(pin));
		break;

	case IDE_PIN_PB14:
		PORTCON_PORTB_SEL1 = (PORTCON_PORTB_SEL1 & ~PORTCON_PORTB_SEL1_B14_MASK) | PORTCON_PORTB_SEL1_B14_BITS_GPIOB14;
		PORTCON_PORTB_IE &= ~PORTCON_PORTB_IE_B14_MASK;
		PORTCON_PORTB_PU &= ~PORTCON_PORTB_PU_B14_MASK;
		PORTCON_PORTB_PD &= ~PORTCON_PORTB_PD_B14_MASK;
		PORTCON_PORTB_OD &= ~PORTCON_PORTB_OD_B14_MASK;
		break;

	// GPIOC pins
	case IDE_PIN_PC3:
		PORTCON_PORTC_SEL0 &= ~PORTCON_PORTC_SEL0_C3_MASK;
		PORTCON_PORTC_IE &= ~PORTCON_PORTC_IE_C3_MASK;
		PORTCON_PORTC_PU &= ~PORTCON_PORTC_PU_C3_MASK;
		PORTCON_PORTC_PD &= ~PORTCON_PORTC_PD_C3_MASK;
		PORTCON_PORTC_OD = (PORTCON_PORTC_OD & ~PORTCON_PORTC_OD_C3_MASK) | PORTCON_PORTC_OD_C3_BITS_DISABLE;
		break;

	case IDE_PIN_PC5:
		PORTCON_PORTC_SEL0 &= ~PORTCON_PORTC_SEL0_C5_MASK;
		if (mode == MINI_PIN_MODE_IN) {
			PORTCON_PORTC_IE |= PORTCON_PORTC_IE_C5_BITS_ENABLE;
			PORTCON_PORTC_PU |= PORTCON_PORTC_PU_C5_BITS_ENABLE;
			PORTCON_PORTC_PD &= ~PORTCON_PORTC_PD_C5_MASK;
			PORTCON_PORTC_OD = (PORTCON_PORTC_OD & ~PORTCON_PORTC_OD_C5_MASK) | PORTCON_PORTC_OD_C5_BITS_ENABLE;
		} else {
			PORTCON_PORTC_IE &= ~PORTCON_PORTC_IE_C5_MASK;
			PORTCON_PORTC_PU &= ~PORTCON_PORTC_PU_C5_MASK;
			PORTCON_PORTC_PD &= ~PORTCON_PORTC_PD_C5_MASK;
			PORTCON_PORTC_OD = (PORTCON_PORTC_OD & ~PORTCON_PORTC_OD_C5_MASK) | PORTCON_PORTC_OD_C5_BITS_DISABLE;
		}
		break;

	// GPIOC free pins (PC6-PC15)
	case IDE_PIN_PC6:
	case IDE_PIN_PC7:
	case IDE_PIN_PC8:
	case IDE_PIN_PC9:
	case IDE_PIN_PC10:
	case IDE_PIN_PC11:
	case IDE_PIN_PC12:
	case IDE_PIN_PC13:
	case IDE_PIN_PC14:
	case IDE_PIN_PC15:
		// Free pins, configure as GPIO with no pull-up/down
		PORTCON_PORTC_SEL0 &= ~(1U << MINI_PinNumber(pin));
		PORTCON_PORTC_IE &= ~(1U << MINI_PinNumber(pin));
		PORTCON_PORTC_PU &= ~(1U << MINI_PinNumber(pin));
		PORTCON_PORTC_PD &= ~(1U << MINI_PinNumber(pin));
		PORTCON_PORTC_OD &= ~(1U << MINI_PinNumber(pin));
		break;

	default:
		break;
	}

	bank = IDE_BOARD_GetBank(pin);
	if (mode == MINI_PIN_MODE_OUT) {
		bank->DIR |= mask;
	} else {
		bank->DIR &= ~mask;
	}
}

void IDE_BOARD_DigitalWrite(mini_pin_t pin, bool value)
{
	volatile GPIO_Bank_t *bank;
	const uint8_t bit = MINI_PinNumber(pin);

	if (!IDE_BOARD_IsSupportedPin(pin)) {
		return;
	}

	bank = IDE_BOARD_GetBank(pin);
	if (value) {
		GPIO_SetBit(&bank->DATA, bit);
	} else {
		GPIO_ClearBit(&bank->DATA, bit);
	}
}

bool IDE_BOARD_DigitalRead(mini_pin_t pin)
{
	volatile GPIO_Bank_t *bank;

	if (!IDE_BOARD_IsSupportedPin(pin)) {
		return false;
	}

	bank = IDE_BOARD_GetBank(pin);
	return GPIO_CheckBit(&bank->DATA, MINI_PinNumber(pin)) != 0U;
}

void IDE_BOARD_BeepStart(uint16_t frequency)
{
	GPIO_ClearBit(&GPIOC->DATA, GPIOC_PIN_AUDIO_PATH);
	SYSTEM_DelayMs(20);
	BK4819_PlayTone(frequency, true);
	SYSTEM_DelayMs(2);
	GPIO_SetBit(&GPIOC->DATA, GPIOC_PIN_AUDIO_PATH);
	BK4819_ExitTxMute();
}

void IDE_BOARD_BeepStop(void)
{
	BK4819_EnterTxMute();
	SYSTEM_DelayMs(20);
	GPIO_ClearBit(&GPIOC->DATA, GPIOC_PIN_AUDIO_PATH);
	SYSTEM_DelayMs(5);
	BK4819_TurnsOffTones_TurnsOnRX();
}

void IDE_BOARD_SleepMs(uint16_t value)
{
	SYSTEM_DelayMs(value);
}
