#include "firmware/mini_board.h"

#include "ARMCM0.h"
#include "bsp/dp32g030/gpio.h"
#include "bsp/dp32g030/portcon.h"
#include "bsp/dp32g030/syscon.h"
#include "driver/gpio.h"
#include "driver/st7565.h"
#include "driver/system.h"
#include "driver/systick.h"

#define IDE_PIN_ENCODE(port, number)  ((((uint8_t)(port)) << 5) | ((number) & 0x1FU))

enum {
	IDE_PIN_PB6  = IDE_PIN_ENCODE(1U, 6U),
	IDE_PIN_PB14 = IDE_PIN_ENCODE(1U, 14U),
	IDE_PIN_PC3  = IDE_PIN_ENCODE(2U, 3U),
	IDE_PIN_PC5  = IDE_PIN_ENCODE(2U, 5U),
};

static volatile GPIO_Bank_t *IDE_BOARD_GetBank(mini_pin_t pin)
{
	switch (pin >> 5) {
	case 0:
		return GPIOA;
	case 1:
		return GPIOB;
	case 2:
		return GPIOC;
	default:
		return GPIOA;
	}
}

static void IDE_BOARD_EnableClocks(void)
{
	SYSCON_DEV_CLK_GATE = 0
		| SYSCON_DEV_CLK_GATE_GPIOA_BITS_ENABLE
		| SYSCON_DEV_CLK_GATE_GPIOB_BITS_ENABLE
		| SYSCON_DEV_CLK_GATE_GPIOC_BITS_ENABLE
		| SYSCON_DEV_CLK_GATE_SPI0_BITS_ENABLE
		;
}

static void IDE_BOARD_InitGpio(void)
{
	GPIOA->DIR |= GPIO_DIR_10_BITS_OUTPUT | GPIO_DIR_11_BITS_OUTPUT | GPIO_DIR_12_BITS_OUTPUT | GPIO_DIR_13_BITS_OUTPUT;
	GPIOA->DIR &= ~(GPIO_DIR_3_MASK | GPIO_DIR_4_MASK | GPIO_DIR_5_MASK | GPIO_DIR_6_MASK);

	GPIOB->DIR |= GPIO_DIR_6_BITS_OUTPUT | GPIO_DIR_9_BITS_OUTPUT | GPIO_DIR_11_BITS_OUTPUT | GPIO_DIR_14_BITS_OUTPUT;
	GPIOB->DIR &= ~(GPIO_DIR_7_MASK | GPIO_DIR_8_MASK | GPIO_DIR_10_MASK);

	GPIOC->DIR |= GPIO_DIR_3_BITS_OUTPUT;
	GPIOC->DIR &= ~(GPIO_DIR_5_MASK);

	GPIO_SetBit(&GPIOA->DATA, 10);
	GPIO_SetBit(&GPIOA->DATA, 11);
	GPIO_ClearBit(&GPIOA->DATA, 12);
	GPIO_SetBit(&GPIOA->DATA, 13);

	GPIO_SetBit(&GPIOB->DATA, 6);
	GPIO_ClearBit(&GPIOB->DATA, 14);
	GPIO_ClearBit(&GPIOC->DATA, 3);
}

static void IDE_BOARD_InitPortcon(void)
{
	PORTCON_PORTA_SEL0 &= ~(PORTCON_PORTA_SEL0_A3_MASK | PORTCON_PORTA_SEL0_A4_MASK | PORTCON_PORTA_SEL0_A5_MASK | PORTCON_PORTA_SEL0_A6_MASK);
	PORTCON_PORTA_SEL0 |= PORTCON_PORTA_SEL0_A3_BITS_GPIOA3 | PORTCON_PORTA_SEL0_A4_BITS_GPIOA4 | PORTCON_PORTA_SEL0_A5_BITS_GPIOA5 | PORTCON_PORTA_SEL0_A6_BITS_GPIOA6;

	PORTCON_PORTA_SEL1 &= ~(PORTCON_PORTA_SEL1_A10_MASK | PORTCON_PORTA_SEL1_A11_MASK | PORTCON_PORTA_SEL1_A12_MASK | PORTCON_PORTA_SEL1_A13_MASK);
	PORTCON_PORTA_SEL1 |= PORTCON_PORTA_SEL1_A10_BITS_GPIOA10 | PORTCON_PORTA_SEL1_A11_BITS_GPIOA11 | PORTCON_PORTA_SEL1_A12_BITS_GPIOA12 | PORTCON_PORTA_SEL1_A13_BITS_GPIOA13;

	PORTCON_PORTB_SEL0 &= ~(PORTCON_PORTB_SEL0_B6_MASK | PORTCON_PORTB_SEL0_B7_MASK);
	PORTCON_PORTB_SEL0 |= PORTCON_PORTB_SEL0_B6_BITS_GPIOB6 | PORTCON_PORTB_SEL0_B7_BITS_SPI0_SSN;

	PORTCON_PORTB_SEL1 &= ~(PORTCON_PORTB_SEL1_B8_MASK | PORTCON_PORTB_SEL1_B9_MASK | PORTCON_PORTB_SEL1_B10_MASK | PORTCON_PORTB_SEL1_B11_MASK | PORTCON_PORTB_SEL1_B14_MASK);
	PORTCON_PORTB_SEL1 |= PORTCON_PORTB_SEL1_B8_BITS_SPI0_CLK | PORTCON_PORTB_SEL1_B9_BITS_GPIOB9 | PORTCON_PORTB_SEL1_B10_BITS_SPI0_MOSI | PORTCON_PORTB_SEL1_B11_BITS_GPIOB11 | PORTCON_PORTB_SEL1_B14_BITS_GPIOB14;

	PORTCON_PORTC_SEL0 &= ~(PORTCON_PORTC_SEL0_C3_MASK | PORTCON_PORTC_SEL0_C5_MASK);

	PORTCON_PORTA_IE |= PORTCON_PORTA_IE_A3_BITS_ENABLE | PORTCON_PORTA_IE_A4_BITS_ENABLE | PORTCON_PORTA_IE_A5_BITS_ENABLE | PORTCON_PORTA_IE_A6_BITS_ENABLE;
	PORTCON_PORTA_IE &= ~(PORTCON_PORTA_IE_A10_MASK | PORTCON_PORTA_IE_A11_MASK | PORTCON_PORTA_IE_A12_MASK | PORTCON_PORTA_IE_A13_MASK);

	PORTCON_PORTA_PU |= PORTCON_PORTA_PU_A3_BITS_ENABLE | PORTCON_PORTA_PU_A4_BITS_ENABLE | PORTCON_PORTA_PU_A5_BITS_ENABLE | PORTCON_PORTA_PU_A6_BITS_ENABLE;
	PORTCON_PORTA_PU &= ~(PORTCON_PORTA_PU_A10_MASK | PORTCON_PORTA_PU_A11_MASK | PORTCON_PORTA_PU_A12_MASK | PORTCON_PORTA_PU_A13_MASK);
	PORTCON_PORTA_PD &= ~(PORTCON_PORTA_PD_A3_MASK | PORTCON_PORTA_PD_A4_MASK | PORTCON_PORTA_PD_A5_MASK | PORTCON_PORTA_PD_A6_MASK | PORTCON_PORTA_PD_A10_MASK | PORTCON_PORTA_PD_A11_MASK | PORTCON_PORTA_PD_A12_MASK | PORTCON_PORTA_PD_A13_MASK);
	PORTCON_PORTA_OD |= PORTCON_PORTA_OD_A3_BITS_ENABLE | PORTCON_PORTA_OD_A4_BITS_ENABLE | PORTCON_PORTA_OD_A5_BITS_ENABLE | PORTCON_PORTA_OD_A6_BITS_ENABLE;
	PORTCON_PORTA_OD &= ~(PORTCON_PORTA_OD_A10_MASK | PORTCON_PORTA_OD_A11_MASK | PORTCON_PORTA_OD_A12_MASK | PORTCON_PORTA_OD_A13_MASK);

	PORTCON_PORTB_IE &= ~(PORTCON_PORTB_IE_B6_MASK | PORTCON_PORTB_IE_B7_MASK | PORTCON_PORTB_IE_B8_MASK | PORTCON_PORTB_IE_B9_MASK | PORTCON_PORTB_IE_B10_MASK | PORTCON_PORTB_IE_B11_MASK | PORTCON_PORTB_IE_B14_MASK);
	PORTCON_PORTB_PU &= ~(PORTCON_PORTB_PU_B6_MASK | PORTCON_PORTB_PU_B7_MASK | PORTCON_PORTB_PU_B8_MASK | PORTCON_PORTB_PU_B9_MASK | PORTCON_PORTB_PU_B10_MASK | PORTCON_PORTB_PU_B11_MASK | PORTCON_PORTB_PU_B14_MASK);
	PORTCON_PORTB_PD &= ~(PORTCON_PORTB_PD_B6_MASK | PORTCON_PORTB_PD_B7_MASK | PORTCON_PORTB_PD_B8_MASK | PORTCON_PORTB_PD_B9_MASK | PORTCON_PORTB_PD_B10_MASK | PORTCON_PORTB_PD_B11_MASK | PORTCON_PORTB_PD_B14_MASK);
	PORTCON_PORTB_OD &= ~(PORTCON_PORTB_OD_B6_MASK | PORTCON_PORTB_OD_B9_MASK | PORTCON_PORTB_OD_B11_MASK | PORTCON_PORTB_OD_B14_MASK);

	PORTCON_PORTC_IE |= PORTCON_PORTC_IE_C5_BITS_ENABLE;
	PORTCON_PORTC_IE &= ~(PORTCON_PORTC_IE_C3_MASK);
	PORTCON_PORTC_PU |= PORTCON_PORTC_PU_C5_BITS_ENABLE;
	PORTCON_PORTC_PU &= ~(PORTCON_PORTC_PU_C3_MASK);
	PORTCON_PORTC_PD &= ~(PORTCON_PORTC_PD_C3_MASK | PORTCON_PORTC_PD_C5_MASK);
	PORTCON_PORTC_OD &= ~(PORTCON_PORTC_OD_C3_MASK);
	PORTCON_PORTC_OD |= PORTCON_PORTC_OD_C3_BITS_DISABLE | PORTCON_PORTC_OD_C5_BITS_ENABLE;
}

void IDE_BOARD_Init(void)
{
	SYSTEM_ConfigureClocks();
	IDE_BOARD_EnableClocks();
	SYSTICK_Init();
	IDE_BOARD_InitPortcon();
	IDE_BOARD_InitGpio();
	ST7565_Init();
	__enable_irq();
}

bool IDE_BOARD_IsSupportedPin(mini_pin_t pin)
{
	return pin == IDE_PIN_PB6 || pin == IDE_PIN_PB14 || pin == IDE_PIN_PC3 || pin == IDE_PIN_PC5;
}

void IDE_BOARD_PinMode(mini_pin_t pin, mini_pin_mode_t mode)
{
	volatile GPIO_Bank_t *bank;
	const uint32_t mask = 1U << MINI_PinNumber(pin);

	if (!IDE_BOARD_IsSupportedPin(pin)) {
		return;
	}

	switch (pin) {
	case IDE_PIN_PB6:
		PORTCON_PORTB_SEL0 = (PORTCON_PORTB_SEL0 & ~PORTCON_PORTB_SEL0_B6_MASK) | PORTCON_PORTB_SEL0_B6_BITS_GPIOB6;
		PORTCON_PORTB_IE &= ~PORTCON_PORTB_IE_B6_MASK;
		PORTCON_PORTB_PU &= ~PORTCON_PORTB_PU_B6_MASK;
		PORTCON_PORTB_PD &= ~PORTCON_PORTB_PD_B6_MASK;
		PORTCON_PORTB_OD &= ~PORTCON_PORTB_OD_B6_MASK;
		break;

	case IDE_PIN_PB14:
		PORTCON_PORTB_SEL1 = (PORTCON_PORTB_SEL1 & ~PORTCON_PORTB_SEL1_B14_MASK) | PORTCON_PORTB_SEL1_B14_BITS_GPIOB14;
		PORTCON_PORTB_IE &= ~PORTCON_PORTB_IE_B14_MASK;
		PORTCON_PORTB_PU &= ~PORTCON_PORTB_PU_B14_MASK;
		PORTCON_PORTB_PD &= ~PORTCON_PORTB_PD_B14_MASK;
		PORTCON_PORTB_OD &= ~PORTCON_PORTB_OD_B14_MASK;
		break;

	case IDE_PIN_PC3:
		PORTCON_PORTC_SEL0 &= ~PORTCON_PORTC_SEL0_C3_MASK;
		PORTCON_PORTC_IE &= ~PORTCON_PORTC_IE_C3_MASK;
		PORTCON_PORTC_PU &= ~PORTCON_PORTC_PU_C3_MASK;
		PORTCON_PORTC_PD &= ~PORTCON_PORTC_PD_C3_MASK;
		PORTCON_PORTC_OD = (PORTCON_PORTC_OD & ~PORTCON_PORTC_OD_C3_MASK) | PORTCON_PORTC_OD_C3_BITS_DISABLE;
		break;

	case IDE_PIN_PC5:
		PORTCON_PORTC_SEL0 &= ~PORTCON_PORTC_SEL0_C5_MASK;
		if (mode == MINI_PIN_MODE_IN) {
			PORTCON_PORTC_IE |= PORTCON_PORTC_IE_C5_BITS_ENABLE;
			PORTCON_PORTC_PU |= PORTCON_PORTC_PU_C5_BITS_ENABLE;
			PORTCON_PORTC_PD &= ~PORTCON_PORTC_PD_C5_MASK;
			PORTCON_PORTC_OD = (PORTCON_PORTC_OD & ~PORTCON_PORTC_OD_C5_MASK) | PORTCON_PORTC_OD_C5_BITS_ENABLE;
		} else {
			PORTCON_PORTC_IE &= ~PORTCON_PORTC_IE_C5_MASK;
			PORTCON_PORTC_PU &= ~PORTCON_PORTC_PU_C5_MASK;
			PORTCON_PORTC_PD &= ~PORTCON_PORTC_PD_C5_MASK;
			PORTCON_PORTC_OD = (PORTCON_PORTC_OD & ~PORTCON_PORTC_OD_C5_MASK) | PORTCON_PORTC_OD_C5_BITS_DISABLE;
		}
		break;

	default:
		break;
	}

	bank = IDE_BOARD_GetBank(pin);
	if (mode == MINI_PIN_MODE_OUT) {
		bank->DIR |= mask;
	} else {
		bank->DIR &= ~mask;
	}
}

void IDE_BOARD_DigitalWrite(mini_pin_t pin, bool value)
{
	volatile GPIO_Bank_t *bank;
	const uint8_t bit = MINI_PinNumber(pin);

	if (!IDE_BOARD_IsSupportedPin(pin)) {
		return;
	}

	bank = IDE_BOARD_GetBank(pin);
	if (value) {
		GPIO_SetBit(&bank->DATA, bit);
	} else {
		GPIO_ClearBit(&bank->DATA, bit);
	}
}

bool IDE_BOARD_DigitalRead(mini_pin_t pin)
{
	volatile GPIO_Bank_t *bank;

	if (!IDE_BOARD_IsSupportedPin(pin)) {
		return false;
	}

	bank = IDE_BOARD_GetBank(pin);
	return GPIO_CheckBit(&bank->DATA, MINI_PinNumber(pin)) != 0U;
}

void IDE_BOARD_SleepMs(uint16_t value)
{
	SYSTEM_DelayMs(value);
}
